# Generated by Django 2.2.1 on 2019-11-07 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191107_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 7, 17, 29, 52, 186635), verbose_name='date published'),
        ),
    ]
