# Generated by Django 2.2.1 on 2019-11-07 17:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191107_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 7, 17, 30, 23, 929890, tzinfo=utc), verbose_name='date published'),
        ),
    ]
